# Generated by Django 5.2 on 2025-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.CharField(blank=True, help_text='Жанры через запятую', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
