# Generated by Django 5.2 on 2025-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_artist_options_artist_country_artist_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обложка альбома', null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, help_text='Описание альбома'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, help_text='Основной жанр альбома', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(default=2023, help_text='Год выпуска альбома'),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, help_text='Точная дата выпуска (если известна)', null=True),
        ),
    ]
