# Generated by Django 5.2 on 2025-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_alter_album_options_remove_album_cover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['album', 'title'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, help_text='Жанр трека', max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, help_text='Текст песни'),
        ),
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
