# Generated by Django 5.2 on 2025-04-26 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_track_options_track_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Дата и время лайка')),
                ('track', models.ForeignKey(help_text='Трек, получивший лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music_app.track')),
                ('user', models.ForeignKey(help_text='Пользователь, поставивший лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='music_app_l_user_id_2efd52_idx'), models.Index(fields=['track'], name='music_app_l_track_i_d534c6_idx'), models.Index(fields=['timestamp'], name='music_app_l_timesta_0fe97b_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
