# Generated by Django 5.2 on 2025-04-26 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Дата и время дизлайка')),
                ('track', models.ForeignKey(help_text='Трек, получивший дизлайк', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='music_app.track')),
                ('user', models.ForeignKey(help_text='Пользователь, поставивший дизлайк', on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дизлайк',
                'verbose_name_plural': 'Дизлайки',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='music_app_d_user_id_c9b215_idx'), models.Index(fields=['track'], name='music_app_d_track_i_659b63_idx'), models.Index(fields=['timestamp'], name='music_app_d_timesta_c75f1d_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
