# Generated by Django 5.2 on 2025-04-26 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Дата и время пропуска трека')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Длительность прослушивания до пропуска (в секундах)')),
                ('track', models.ForeignKey(help_text='Пропущенный трек', on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='music_app.track')),
                ('user', models.ForeignKey(help_text='Пользователь, пропустивший трек', on_delete=django.db.models.deletion.CASCADE, related_name='skips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пропуск трека',
                'verbose_name_plural': 'Пропуски треков',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='music_app_s_user_id_d04c77_idx'), models.Index(fields=['track'], name='music_app_s_track_i_0ff6b3_idx'), models.Index(fields=['timestamp'], name='music_app_s_timesta_16adbc_idx'), models.Index(fields=['duration'], name='music_app_s_duratio_57dbe4_idx')],
            },
        ),
    ]
