# Generated by Django 5.2 on 2025-04-26 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время генерации рекомендации')),
                ('score', models.FloatField(default=0.0, help_text='Оценка/вероятность рекомендации (от 0 до 1)')),
                ('is_viewed', models.BooleanField(default=False, help_text='Просмотрел ли пользователь рекомендацию')),
                ('is_clicked', models.BooleanField(default=False, help_text='Перешел ли пользователь к рекомендуемому треку')),
                ('source', models.CharField(default='system', help_text='Источник рекомендации (система/коллаборативная фильтрация/контентная и т.д.)', max_length=50)),
                ('track', models.ForeignKey(help_text='Рекомендуемый трек', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='music_app.track')),
                ('user', models.ForeignKey(help_text='Пользователь, которому рекомендуется трек', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='music_app_r_user_id_ce2c9a_idx'), models.Index(fields=['track'], name='music_app_r_track_i_a020f9_idx'), models.Index(fields=['created_at'], name='music_app_r_created_80c0b2_idx'), models.Index(fields=['score'], name='music_app_r_score_02a9df_idx'), models.Index(fields=['is_viewed'], name='music_app_r_is_view_f255d6_idx'), models.Index(fields=['source'], name='music_app_r_source_32b4a2_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
